services:
  - type: web
    name: viego-backend
    env: python
    region: singapore
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn --worker-class eventlet -w 1 --config gunicorn_config.py main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
